name: Build and Deploy Factorial App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker
        run: |
          docker build -t factorial-app .
          docker images

      - name: Push Docker Image (Optional)
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
          docker tag factorial-app your-docker-username/factorial-app:latest
          docker push your-docker-username/factorial-app:latest
