name: Build and Deploy Factorial App

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Debug: List files
        run: ls -la

      - name: Set up Docker
        run: |
          docker build -t factorial-app .
          docker images

      - name: Push Docker Image (Opt
